name: Test formula

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test Authometry formula
        run: |
          brew tap-new authometry/test
          cp Formula/authometry.rb "$(brew --repository authometry/test)/Formula/authometry.rb"
          brew install authometry/test/authometry
          brew test authometry/test/authometry
